package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseIssuesHistories generated by hbm2java
 */
public class CaseIssuesHistories implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private int issueId;
	private String action;
	private Integer caseId;
	private Integer oldIssueTypeId;
	private Integer newIssueTypeId;
	private String oldComments;
	private String newComments;
	private Integer oldStatusId;
	private Integer newStatusId;
	private Date oldCompletedDate;
	private Date newCompletedDate;
	private Integer createdUserId;

	public CaseIssuesHistories() {
	}

	public CaseIssuesHistories(int issueId, String action) {
		this.issueId = issueId;
		this.action = action;
	}

	public CaseIssuesHistories(int issueId, String action, Integer caseId,
			Integer oldIssueTypeId, Integer newIssueTypeId, String oldComments,
			String newComments, Integer oldStatusId, Integer newStatusId,
			Date oldCompletedDate, Date newCompletedDate, Integer createdUserId) {
		this.issueId = issueId;
		this.action = action;
		this.caseId = caseId;
		this.oldIssueTypeId = oldIssueTypeId;
		this.newIssueTypeId = newIssueTypeId;
		this.oldComments = oldComments;
		this.newComments = newComments;
		this.oldStatusId = oldStatusId;
		this.newStatusId = newStatusId;
		this.oldCompletedDate = oldCompletedDate;
		this.newCompletedDate = newCompletedDate;
		this.createdUserId = createdUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getIssueId() {
		return this.issueId;
	}

	public void setIssueId(int issueId) {
		this.issueId = issueId;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public Integer getOldIssueTypeId() {
		return this.oldIssueTypeId;
	}

	public void setOldIssueTypeId(Integer oldIssueTypeId) {
		this.oldIssueTypeId = oldIssueTypeId;
	}

	public Integer getNewIssueTypeId() {
		return this.newIssueTypeId;
	}

	public void setNewIssueTypeId(Integer newIssueTypeId) {
		this.newIssueTypeId = newIssueTypeId;
	}

	public String getOldComments() {
		return this.oldComments;
	}

	public void setOldComments(String oldComments) {
		this.oldComments = oldComments;
	}

	public String getNewComments() {
		return this.newComments;
	}

	public void setNewComments(String newComments) {
		this.newComments = newComments;
	}

	public Integer getOldStatusId() {
		return this.oldStatusId;
	}

	public void setOldStatusId(Integer oldStatusId) {
		this.oldStatusId = oldStatusId;
	}

	public Integer getNewStatusId() {
		return this.newStatusId;
	}

	public void setNewStatusId(Integer newStatusId) {
		this.newStatusId = newStatusId;
	}

	public Date getOldCompletedDate() {
		return this.oldCompletedDate;
	}

	public void setOldCompletedDate(Date oldCompletedDate) {
		this.oldCompletedDate = oldCompletedDate;
	}

	public Date getNewCompletedDate() {
		return this.newCompletedDate;
	}

	public void setNewCompletedDate(Date newCompletedDate) {
		this.newCompletedDate = newCompletedDate;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

}
