package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClientDisabilities generated by hbm2java
 */
public class ClientDisabilities implements java.io.Serializable {

	private Integer id;
//	private Integer contactId;
//	private Integer disabilityId;
	private Contacts contact;
	private DisabilityTypes disabilityType;
	private String comments;
	private String primaryFlag;

	public ClientDisabilities() {
	}

	/**
	 * @param id
	 * @param contact
	 * @param disabilityType
	 * @param comments
	 * @param primaryFlag
	 */
	public ClientDisabilities(Integer id, Contacts contact,
			DisabilityTypes disabilityType, String comments, String primaryFlag) {
		this.id = id;
		this.contact = contact;
		this.disabilityType = disabilityType;
		this.comments = comments;
		this.primaryFlag = primaryFlag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

//	public Integer getContactId() {
//		return this.contactId;
//	}
//
//	public void setContactId(Integer contactId) {
//		this.contactId = contactId;
//	}
//
//	public Integer getDisabilityId() {
//		return this.disabilityId;
//	}
//
//	public void setDisabilityId(Integer disabilityId) {
//		this.disabilityId = disabilityId;
//	}

	/**
	 * @return the contact
	 */
	public Contacts getContact() {
		return contact;
	}

	/**
	 * @param contact the contact to set
	 */
	public void setContact(Contacts contact) {
		this.contact = contact;
	}

	/**
	 * @return the disabilityType
	 */
	public DisabilityTypes getDisabilityType() {
		return disabilityType;
	}

	/**
	 * @param disabilityType the disabilityType to set
	 */
	public void setDisabilityType(DisabilityTypes disabilityType) {
		this.disabilityType = disabilityType;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getPrimaryFlag() {
		return this.primaryFlag;
	}

	public void setPrimaryFlag(String primaryFlag) {
		this.primaryFlag = primaryFlag;
	}

}
