package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * CommunicationTypes generated by hbm2java
 */
public class CommunicationTypes implements java.io.Serializable {

	private Integer id;
	private String communicationTypeName;

	public CommunicationTypes() {
	}

	public CommunicationTypes(String communicationTypeName) {
		this.communicationTypeName = communicationTypeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCommunicationTypeName() {
		return this.communicationTypeName;
	}

	public void setCommunicationTypeName(String communicationTypeName) {
		this.communicationTypeName = communicationTypeName;
	}

}
