package data;

// Generated Jul 28, 2014 4:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * ContactTypes generated by hbm2java
 */
public class ContactTypes implements java.io.Serializable {

	private Integer id;
	private String contactTypeName;
	private String contactTypeDescription;

	public ContactTypes() {
	}

	public ContactTypes(String contactTypeName, String contactTypeDescription) {
		this.contactTypeName = contactTypeName;
		this.contactTypeDescription = contactTypeDescription;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContactTypeName() {
		return this.contactTypeName;
	}

	public void setContactTypeName(String contactTypeName) {
		this.contactTypeName = contactTypeName;
	}

	public String getContactTypeDescription() {
		return this.contactTypeDescription;
	}

	public void setContactTypeDescription(String contactTypeDescription) {
		this.contactTypeDescription = contactTypeDescription;
	}

}
