package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * CriteriaControlValues generated by hbm2java
 */
public class CriteriaControlValues implements java.io.Serializable {

	private Integer id;
	private Integer criteriaControlId;
	private String value;

	public CriteriaControlValues() {
	}

	public CriteriaControlValues(Integer criteriaControlId, String value) {
		this.criteriaControlId = criteriaControlId;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCriteriaControlId() {
		return this.criteriaControlId;
	}

	public void setCriteriaControlId(Integer criteriaControlId) {
		this.criteriaControlId = criteriaControlId;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
