package data;

// Generated Jul 28, 2014 4:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * EnquiryIssues generated by hbm2java
 */
public class EnquiryIssues implements java.io.Serializable {

	private Integer id;
	private Integer enquiryId;
	private Integer issueId;

	public EnquiryIssues() {
	}

	public EnquiryIssues(Integer enquiryId, Integer issueId) {
		this.enquiryId = enquiryId;
		this.issueId = issueId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getEnquiryId() {
		return this.enquiryId;
	}

	public void setEnquiryId(Integer enquiryId) {
		this.enquiryId = enquiryId;
	}

	public Integer getIssueId() {
		return this.issueId;
	}

	public void setIssueId(Integer issueId) {
		this.issueId = issueId;
	}

}
