package data;

import java.util.HashSet;
import java.util.Set;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * EnquiryIssues generated by hbm2java
 */
public class EnquiryIssues implements java.io.Serializable {

	private Integer id;
//	private Integer enquiryId;
//	private Integer issueId;
	private Enquiries enquiry;
	private IssueTypes issue;
	private String comment;
	/**
	 * 
	 */
	public EnquiryIssues() {
		// TODO Auto-generated constructor stub
	}
	/**
	 * @param id
	 * @param enquiry
	 * @param issue
	 * @param comment
	 */
	public EnquiryIssues(Integer id, Enquiries enquiry, IssueTypes issue,
			String comment) {
		this.id = id;
		this.enquiry = enquiry;
		this.issue = issue;
		this.comment = comment;
	}
	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}
/**
	 * @return the enquiry
	 */
	public Enquiries getEnquiry() {
		return enquiry;
	}
	/**
	 * @param enquiry the enquiry to set
	 */
	public void setEnquiry(Enquiries enquiry) {
		this.enquiry = enquiry;
	}
	/**
	 * @return the issue
	 */
	public IssueTypes getIssue() {
		return issue;
	}
	/**
	 * @param issue the issue to set
	 */
	public void setIssue(IssueTypes issue) {
		this.issue = issue;
	}
	//	/**
//	 * @return the enquiryId
//	 */
//	public Integer getEnquiryId() {
//		return enquiryId;
//	}
//	/**
//	 * @param enquiryId the enquiryId to set
//	 */
//	public void setEnquiryId(Integer enquiryId) {
//		this.enquiryId = enquiryId;
//	}
//	/**
//	 * @return the issueId
//	 */
//	public Integer getIssueId() {
//		return issueId;
//	}
//	/**
//	 * @param issueId the issueId to set
//	 */
//	public void setIssueId(Integer issueId) {
//		this.issueId = issueId;
//	}
	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}
	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	

}
