package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventPersonId generated by hbm2java
 */
public class EventPersonId implements java.io.Serializable {

	private long eventId;
	private long personId;

	public EventPersonId() {
	}

	public EventPersonId(long eventId, long personId) {
		this.eventId = eventId;
		this.personId = personId;
	}

	public long getEventId() {
		return this.eventId;
	}

	public void setEventId(long eventId) {
		this.eventId = eventId;
	}

	public long getPersonId() {
		return this.personId;
	}

	public void setPersonId(long personId) {
		this.personId = personId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventPersonId))
			return false;
		EventPersonId castOther = (EventPersonId) other;

		return (this.getEventId() == castOther.getEventId())
				&& (this.getPersonId() == castOther.getPersonId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEventId();
		result = 37 * result + (int) this.getPersonId();
		return result;
	}

}
