package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventPerson generated by hbm2java
 */
public class EventPerson implements java.io.Serializable {

	private EventPersonId id;
	private People people;

	public EventPerson() {
	}

	public EventPerson(EventPersonId id, People people) {
		this.id = id;
		this.people = people;
	}

	public EventPersonId getId() {
		return this.id;
	}

	public void setId(EventPersonId id) {
		this.id = id;
	}

	public People getPeople() {
		return this.people;
	}

	public void setPeople(People people) {
		this.people = people;
	}

}
