package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Events generated by hbm2java
 */
public class Events implements java.io.Serializable {

	private Integer id;
	private Date startTime;
	private Date endTime;
	private Date date;
	private String description;
	private Integer contactLinkId;
	private Integer caseLinkId;
	private Date updatedDateTime;
	private Integer updatedUserId;
	private Integer createdUserId;
	private Date createdDateTime;
	private String name;

	public Events() {
	}

	public Events(Date startTime, Date endTime, Date date, String description,
			Integer contactLinkId, Integer caseLinkId, Date updatedDateTime,
			Integer updatedUserId, Integer createdUserId, Date createdDateTime,
			String name) {
		this.startTime = startTime;
		this.endTime = endTime;
		this.date = date;
		this.description = description;
		this.contactLinkId = contactLinkId;
		this.caseLinkId = caseLinkId;
		this.updatedDateTime = updatedDateTime;
		this.updatedUserId = updatedUserId;
		this.createdUserId = createdUserId;
		this.createdDateTime = createdDateTime;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getContactLinkId() {
		return this.contactLinkId;
	}

	public void setContactLinkId(Integer contactLinkId) {
		this.contactLinkId = contactLinkId;
	}

	public Integer getCaseLinkId() {
		return this.caseLinkId;
	}

	public void setCaseLinkId(Integer caseLinkId) {
		this.caseLinkId = caseLinkId;
	}

	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

	public Integer getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(Integer updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
