package data;

// Generated Jul 28, 2014 4:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * GenderTypes generated by hbm2java
 */
public class GenderTypes implements java.io.Serializable {

	private Integer id;
	private String genderName;
	private String genderCode;

	public GenderTypes() {
	}

	public GenderTypes(String genderName, String genderCode) {
		this.genderName = genderName;
		this.genderCode = genderCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGenderName() {
		return this.genderName;
	}

	public void setGenderName(String genderName) {
		this.genderName = genderName;
	}

	public String getGenderCode() {
		return this.genderCode;
	}

	public void setGenderCode(String genderCode) {
		this.genderCode = genderCode;
	}

}
