package data;

// Generated Jul 28, 2014 4:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * GoalTypes generated by hbm2java
 */
public class GoalTypes implements java.io.Serializable {

	private Integer id;
	private String goalTypeName;

	public GoalTypes() {
	}

	public GoalTypes(String goalTypeName) {
		this.goalTypeName = goalTypeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGoalTypeName() {
		return this.goalTypeName;
	}

	public void setGoalTypeName(String goalTypeName) {
		this.goalTypeName = goalTypeName;
	}

}
