package data;

// Generated Jul 28, 2014 4:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * IacaseEnquiryMappings generated by hbm2java
 */
public class IacaseEnquiryMappings implements java.io.Serializable {

	private Integer id;
	private Integer caseId;
	private Integer enquiryId;

	public IacaseEnquiryMappings() {
	}

	public IacaseEnquiryMappings(Integer caseId, Integer enquiryId) {
		this.caseId = caseId;
		this.enquiryId = enquiryId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public Integer getEnquiryId() {
		return this.enquiryId;
	}

	public void setEnquiryId(Integer enquiryId) {
		this.enquiryId = enquiryId;
	}

}
