package data;

// Generated Jul 28, 2014 4:20:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * IssueTypes generated by hbm2java
 */
public class IssueTypes implements java.io.Serializable {

	private Integer id;
	private String issueName;
	private String issueDescription;

	public IssueTypes() {
	}

	public IssueTypes(String issueName) {
		this.issueName = issueName;
	}

	public IssueTypes(String issueName, String issueDescription) {
		this.issueName = issueName;
		this.issueDescription = issueDescription;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIssueName() {
		return this.issueName;
	}

	public void setIssueName(String issueName) {
		this.issueName = issueName;
	}

	public String getIssueDescription() {
		return this.issueDescription;
	}

	public void setIssueDescription(String issueDescription) {
		this.issueDescription = issueDescription;
	}

}
