package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * People generated by hbm2java
 */
public class People implements java.io.Serializable {

	private Long id;
	private String name;
	private Set eventPersons = new HashSet(0);

	public People() {
	}

	public People(String name, Set eventPersons) {
		this.name = name;
		this.eventPersons = eventPersons;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getEventPersons() {
		return this.eventPersons;
	}

	public void setEventPersons(Set eventPersons) {
		this.eventPersons = eventPersons;
	}

}
