package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * PlanDevelopers generated by hbm2java
 */
public class PlanDevelopers implements java.io.Serializable {

	private Integer id;
	private Integer planId;
	private Integer contactId;

	public PlanDevelopers() {
	}

	public PlanDevelopers(Integer planId, Integer contactId) {
		this.planId = planId;
		this.contactId = contactId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPlanId() {
		return this.planId;
	}

	public void setPlanId(Integer planId) {
		this.planId = planId;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

}
