package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * Risks generated by hbm2java
 */
public class Risks implements java.io.Serializable {

	private Integer id;
	private String riskDescription;
	private String riskManagement;
//	private Integer caseId;
	private IndividualCases individualCase;
	
	
	/**
	 * 
	 */
	public Risks() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param id
	 * @param riskDescription
	 * @param riskManagement
	 * @param individualCase
	 */
	public Risks(Integer id, String riskDescription, String riskManagement,
			IndividualCases individualCase) {
		this.id = id;
		this.riskDescription = riskDescription;
		this.riskManagement = riskManagement;
		this.individualCase = individualCase;
	}
	
	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * @return the riskDescription
	 */
	public String getRiskDescription() {
		return riskDescription;
	}
	/**
	 * @param riskDescription the riskDescription to set
	 */
	public void setRiskDescription(String riskDescription) {
		this.riskDescription = riskDescription;
	}
	/**
	 * @return the riskManagement
	 */
	public String getRiskManagement() {
		return riskManagement;
	}
	/**
	 * @param riskManagement the riskManagement to set
	 */
	public void setRiskManagement(String riskManagement) {
		this.riskManagement = riskManagement;
	}
	/**
	 * @return the individualCase
	 */
	public IndividualCases getIndividualCase() {
		return individualCase;
	}
	/**
	 * @param individualCase the individualCase to set
	 */
	public void setIndividualCase(IndividualCases individualCase) {
		this.individualCase = individualCase;
	}

	

}
