package data;

// Generated Aug 6, 2014 9:58:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * StatusTypes generated by hbm2java
 */
public class StatusTypes implements java.io.Serializable {

	private Integer id;
	private String statusName;

	public StatusTypes() {
	}

	public StatusTypes(String statusName) {
		this.statusName = statusName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

}
